# Generated by Django 5.0.4 on 2026-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_role', models.CharField(choices=[('software_engineer', 'Software Engineer'), ('data_scientist', 'Data Scientist'), ('web_developer', 'Web Developer'), ('devops_engineer', 'DevOps Engineer'), ('ml_engineer', 'Machine Learning Engineer'), ('product_manager', 'Product Manager'), ('ui_ux_designer', 'UI/UX Designer'), ('cybersecurity_analyst', 'Cybersecurity Analyst'), ('cloud_architect', 'Cloud Architect'), ('data_analyst', 'Data Analyst'), ('android_developer', 'Android Developer'), ('ios_developer', 'iOS Developer'), ('blockchain_developer', 'Blockchain Developer'), ('full_stack_developer', 'Full Stack Developer'), ('backend_developer', 'Backend Developer')], max_length=50)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher (0-1 year)'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid-Level (3-5 years)'), ('senior', 'Senior (5+ years)')], max_length=20)),
                ('current_skills', models.TextField()),
                ('skill_score', models.FloatField(default=0)),
                ('gap_skills', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Analyses',
                'ordering': ['-skill_score', '-created_at'],
            },
        ),
    ]
